# Generated by Django 6.0.7 on 2026-07-28 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('scan_date', models.DateTimeField()),
                ('engine_version', models.CharField(max_length=20)),
                ('scanner_version', models.CharField(max_length=20)),
                ('rules_version', models.CharField(max_length=20)),
                ('scan_type', models.CharField(max_length=100)),
                ('laboratory_security_score', models.IntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField()),
                ('security_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=30)),
                ('risk_categories', models.JSONField(default=list)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='audits.audit')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='AuditStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('high', models.IntegerField()),
                ('medium', models.IntegerField()),
                ('low', models.IntegerField()),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='audits.audit')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('points', models.IntegerField()),
                ('audit_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.auditdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audits.audit')),
            ],
        ),
    ]
