# Generated by Django 6.0.7 on 2026-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='comparison_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='cve_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='cvss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='source',
            field=models.CharField(default='rule', max_length=50),
        ),
    ]
