# Generated by Django 6.0.7 on 2026-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_audit_comparison_data_finding_cve_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='fixed_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
